title: "[WIP] Prabin Lamichhane"
description: Personal portfolio website
logo: /assets/img/logo.png
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
# domain: prabin-lc.github.io
# url: https://prabin-lc.github.io
